[theme]
primaryColor = "#EE7224"
backgroundColor = "#0B0F19"
secondaryBackgroundColor = "#131B2E"
textColor = "#F1F5F9"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50
